### PR TITLE
Return values and help pages

### LINKED ISSUE #46: Add @return to documentation and explicitly use return() when returning values, join help pages

### PR DESCRIPTION
**Pull request by mateuszwyszynski**
This resolves #46

### CODE REVIEW

**Comment by achubaty** [comment]
I don't want this going to `master` yet! I want to review a number of pieces, including the removal of our previously used functions that were in the `development` branch.

**Comment by achubaty** [comment]
`master` and `development` branches need to work, so please don't merge anything into these branches without verifying that all checks pass.

**Comment by achubaty** [comment]
I think this PR needs to be made against `develop` once #37 is merged, not against `master`. It introduces too many breaking changes and is still a work in progress.

**Comment by DamianRodziewicz** [comment]
@achubaty - yes it was meant to be set against develop. Develop is work in progress. We're not going to merge anything to master or development through the process. We'll make one merge after the last sprint and only after all the checks pass and documentation is written.

**Review by DamianRodziewicz — CHANGES_REQUESTED** [review]
LGTM, please fix conflicts and feel free to merge.

**Review by DamianRodziewicz — APPROVED** [review]

**Pull request merged**
